from agents.base_agent import BaseAgent
import json
import re

class AuditorAgent(BaseAgent):
    """
    High-precision QA Evaluation Agent.
    Task: Grade AI responses against ground truth (Context) and a strict Rubric.
    """
    
    def __init__(self, call_gemini_fn=None):
        super().__init__(
            name="AUDITOR",
            role="HQ Evaluation & Hallucination Guard",
            expertise=["Accuracy Auditing", "Hallucination Detection", "Technical Style Review"],
            call_gemini_fn=call_gemini_fn
        )
        
    def can_handle(self, query, context):
        # Auditor is usually triggered programmatically, not via user query directly
        return False
        
    def analyze(self, query, context):
        """
        Evaluate an AI response based on the provided rubric.
        Expects context to contain:
            - target_query: The original user question (or item name for dossiers)
            - target_context: The ground truth / RAG data provided to the original agent
            - target_response: The output generated by the original agent
            - audit_type: Optional string (CHAT, DOSSIER, SOCIAL) to specialize rubric
        """
        user_query = context.get('target_query', 'N/A')
        retrieved_context = context.get('target_context', 'N/A')
        ai_response = context.get('target_response', 'N/A')
        audit_type = context.get('audit_type', 'CHAT')
        
        # Specialize the subject label based on audit type
        subject_label = "AI Response"
        if audit_type == 'DOSSIER':
            subject_label = "Dossier Verdict"
        elif audit_type == 'SOCIAL':
            subject_label = "Social Intelligence Brief"

        prompt = f"""
### ROLE
You are a high-precision QA Evaluation Agent. Your task is to grade the {subject_label} based on the provided Context and Rubric.

### INPUT DATA
1. **Subject/Query:** {user_query}
2. **Ground Truth Context:** {retrieved_context}
3. **{subject_label}:** {ai_response}

### EVALUATION RUBRIC
Grade the content from 1-5 on the following dimensions (1=Poor, 5=Perfect):
- **Grounding:** Is every claim in the {subject_label} supported by the Ground Truth Context? (Hallucination check)
- **Completeness:** Does it adequately cover the key data points from the context?
- **Tone/Style:** Does it follow the required technical formatting and professional tone?

### OUTPUT FORMAT
You MUST return a valid JSON object. No other text.
{{
  "scores": {{ "grounding": int, "completeness": int, "style": int }},
  "reasoning": "Brief explanation of deductions",
  "hallucinations_identified": ["list specific inaccuracies found"],
  "verdict": "PASS" | "FAIL"
}}

A PASS requires grounding >= 4 and completeness >= 3.
"""
        
        if not self.call_gemini_fn:
            return {"success": False, "error": "Neural Link not initialized (Gemini function missing)"}
            
        try:
            raw_response = self.call_gemini_fn(prompt)
            # Try to extract JSON if it's wrapped in markers
            json_match = re.search(r'(\{.*\})', raw_response, re.DOTALL)
            if json_match:
                result = json.loads(json_match.group(1))
            else:
                result = json.loads(raw_response)
                
            return {
                "success": True,
                "audit": result,
                "responder_id": self.name,
                "data_provenance": "NEURAL_AUDIT"
            }
        except Exception as e:
            return {
                "success": False,
                "error": f"Audit Failure: {str(e)}",
                "raw_response": raw_response if 'raw_response' in locals() else None
            }

    def get_example_queries(self):
        return ["INTERNAL_AUDIT_PROTOCOL_X1"]
